dist: xenial
language: cpp
compiler: gcc
sudo: required
cache: apt

before_install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.2-xenial
 - sudo apt-get update
 - sudo apt-get install qt511base qt511tools libgl1-mesa-dev
 - source /opt/qt511/bin/qt511-env.sh

script:
 - cd Source
 - qmake All.pro
 - make
 - cp QtIrbis/lib* IrbisTests/
 - cd IrbisTests
 - ldd IrbisTests
 - ./IrbisTests

