version: 0.0.1.{build}
platform: x64
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

build_script:
  - compile.bat

artifacts:
  - path: Source\QtIrbis\release
    name: Binaries
  - path: Source\QtTests\release
    name: Tests

